server:
  port: 8800

#自定义属性
canal:
  client:
    configs:
      - isCluster: false
        zkServers: 10.26.27.81:2181
        url: 10.26.27.81
        port: 11111
        destination: example
        username:
        password:
        bootstrapServer: 10.26.27.81:2181
        topic:
      - isCluster: false
        zkServers: 10.26.27.81:2181
        url: 10.26.27.81
        port: 11111
        destination: rent_plat
        username:
        password:
        bootstrapServer: 10.26.27.81:2181
        topic: