server:
  port: 8800

#自定义属性
canal:
  client:
    isCluster: false
    zkServers: 10.26.27.81:2181
    url: 10.26.27.81
    port: 11111
    destinations:
      - example
      - rent_plat
    username:
    password: